# Compatibility only: operations absent from the 2026-09-07 snapshot. Baseline a5d424758f6efaccdfa969bd03106ba73dbe1309.
openapi: 3.0.1
info:
  title: 'Заказы Самовывоз'
  x-file-name: in-store-pickup
  description: |
    Управление [сборочными заданиями](/openapi/in-store-pickup#tag/Sborochnye-zadaniya-Samovyvoz) и [метаданными](/openapi/in-store-pickup#tag/Metadannye-Samovyvoz) заказов модели Самовывоз.
  version: instorepickup
paths:
  '/api/v3/click-collect/orders/{orderId}/confirm':
    patch:
      x-readonly-method: false
      x-category: marketplace
      tags:
        - 'Сборочные задания Самовывоз'
      summary: 'Перевести на сборку'
      deprecated: true
      description: |
        Данный метод устарел. Он будет удалён [19 мая](https://dev.wildberries.ru/release-notes?id=474)
      parameters:
        -
          name: orderId
          in: path
          description: 'ID сборочного задания'
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Подтверждено
        400:
          description: 'Неправильный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                IncorrectParameter:
                  $ref: '#/components/examples/IncorrectParameter'
        401:
          $ref: '#/components/responses/401'
        402:
          $ref: '#/components/responses/402'
        403:
          $ref: '#/components/responses/AccessDenied'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          description: 'Ошибка обновления статуса'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                StatusMismatch:
                  $ref: '#/components/examples/StatusMismatch'
        429:
          $ref: '#/components/responses/429'
  '/api/v3/click-collect/orders/{orderId}/prepare':
    patch:
      x-readonly-method: false
      x-category: marketplace
      tags:
        - 'Сборочные задания Самовывоз'
      summary: 'Сообщить, что сборочное задание готово к выдаче'
      deprecated: true
      description: |
        Данный метод устарел. Он будет удалён [19 мая](https://dev.wildberries.ru/release-notes?id=474)
      parameters:
        -
          name: orderId
          in: path
          description: 'ID сборочного задания'
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Подтверждено
        400:
          description: 'Неправильный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                IncorrectParameter:
                  $ref: '#/components/examples/IncorrectParameter'
        401:
          $ref: '#/components/responses/401'
        402:
          $ref: '#/components/responses/402'
        403:
          $ref: '#/components/responses/AccessDenied'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          description: 'Ошибка обновления статуса'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                StatusMismatch:
                  $ref: '#/components/examples/StatusMismatch'
        429:
          $ref: '#/components/responses/429'
  '/api/v3/click-collect/orders/{orderId}/receive':
    patch:
      x-readonly-method: false
      x-category: marketplace
      tags:
        - 'Сборочные задания Самовывоз'
      summary: 'Сообщить, что заказ принят покупателем'
      deprecated: true
      description: |
        Данный метод устарел. Он будет удалён [19 мая](https://dev.wildberries.ru/release-notes?id=474)
      parameters:
        -
          name: orderId
          in: path
          description: 'ID сборочного задания'
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Подтверждено
        400:
          description: 'Неправильный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                IncorrectParameter:
                  $ref: '#/components/examples/IncorrectParameter'
        401:
          $ref: '#/components/responses/401'
        402:
          $ref: '#/components/responses/402'
        403:
          $ref: '#/components/responses/AccessDenied'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          description: 'Ошибка обновления статуса'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                StatusMismatch:
                  $ref: '#/components/examples/StatusMismatch'
        429:
          $ref: '#/components/responses/429'
  '/api/v3/click-collect/orders/{orderId}/reject':
    patch:
      x-readonly-method: false
      x-category: marketplace
      tags:
        - 'Сборочные задания Самовывоз'
      summary: 'Сообщить, что покупатель отказался от заказа'
      deprecated: true
      description: |
        Данный метод устарел. Он будет удалён [19 мая](https://dev.wildberries.ru/release-notes?id=474)
      parameters:
        -
          name: orderId
          in: path
          description: 'ID сборочного задания'
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Подтверждено
        400:
          description: 'Неправильный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                IncorrectParameter:
                  $ref: '#/components/examples/IncorrectParameter'
        401:
          $ref: '#/components/responses/401'
        402:
          $ref: '#/components/responses/402'
        403:
          $ref: '#/components/responses/AccessDenied'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          description: 'Ошибка обновления статуса'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                StatusMismatch:
                  $ref: '#/components/examples/StatusMismatch'
        429:
          $ref: '#/components/responses/429'
  /api/v3/click-collect/orders/status:
    post:
      x-readonly-method: true
      x-category: marketplace
      tags:
        - 'Сборочные задания Самовывоз'
      summary: 'Получить статусы сборочных заданий'
      deprecated: true
      description: |
        Данный метод устарел. Он будет удалён [19 мая](https://dev.wildberries.ru/release-notes?id=474)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api.OrdersRequest'
        required: true
      responses:
        200:
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.OrderStatuses'
        400:
          description: 'Неправильный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                IncorrectRequestBody:
                  $ref: '#/components/examples/IncorrectRequestBody'
        401:
          $ref: '#/components/responses/401'
        402:
          $ref: '#/components/responses/402'
        403:
          $ref: '#/components/responses/AccessDenied'
        429:
          $ref: '#/components/responses/429'
  '/api/v3/click-collect/orders/{orderId}/cancel':
    patch:
      x-readonly-method: false
      x-category: marketplace
      tags:
        - 'Сборочные задания Самовывоз'
      summary: 'Отменить сборочное задание'
      deprecated: true
      description: |
        Данный метод устарел. Он будет удалён [19 мая](https://dev.wildberries.ru/release-notes?id=474)
      parameters:
        -
          name: orderId
          in: path
          description: 'ID сборочного задания'
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Отменено
        400:
          description: 'Неправильный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                IncorrectRequestBody:
                  $ref: '#/components/examples/IncorrectRequestBody'
        401:
          $ref: '#/components/responses/401'
        402:
          $ref: '#/components/responses/402'
        403:
          $ref: '#/components/responses/AccessDenied'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          description: 'Ошибка обновления статуса'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                StatusMismatch:
                  $ref: '#/components/examples/StatusMismatch'
        429:
          $ref: '#/components/responses/429'
  /api/marketplace/v3/click-collect/orders/meta/info:
    post:
      x-readonly-method: true
      x-category: marketplace
      tags:
        - 'Метаданные Самовывоз'
      summary: 'Получить метаданные сборочных заданий'
      description: |
        Метод возвращает метаданные [сборочных заданий](/openapi/in-store-pickup#tag/Sborochnye-zadaniya-Samovyvoz).
        <br><br>
        Перечень метаданных, доступных для сборочного задания, можно получить в [списке новых сборочных заданий](/openapi/in-store-pickup#tag/Sborochnye-zadaniya-Samovyvoz/paths/~1api~1v3~1click-collect~1orders~1new/get), поле `requiredMeta`.
        <br><br>

        <div class="description_limit">
        <a href="/openapi/api-information#tag/Vvedenie/Limity-zaprosov">Лимит запросов</a> на один аккаунт продавца для всех методов <strong>получения и удаления метаданных Самовывоз</strong>:

        | Период | Лимит | Интервал | Всплеск |
        | --- | --- | --- | --- |
        | 1 мин | 150 запросов | 400 мс | 20 запросов |

        Один запрос с кодом ответа <code>409</code> учитывается как 10 запросов
        </div>
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api.OrdersRequestV2'
      responses:
        200:
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.OrdersMetaResponse'
        400:
          $ref: '#/components/responses/IncorrectRequest'
        401:
          $ref: '#/components/responses/401'
        403:
          $ref: '#/components/responses/AccessDeniedBatch'
        429:
          $ref: '#/components/responses/429'
  '/api/v3/click-collect/orders/{orderId}/meta':
    get:
      x-readonly-method: true
      x-category: marketplace
      tags:
        - 'Метаданные Самовывоз'
      summary: 'Получить метаданные сборочного задания'
      deprecated: true
      description: |
        Данный метод устарел. Он будет удалён [19 мая](https://dev.wildberries.ru/release-notes?id=474)
      parameters:
        -
          name: orderId
          in: path
          description: 'ID сборочного задания'
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.OrdersMeta'
        401:
          $ref: '#/components/responses/401'
        402:
          $ref: '#/components/responses/402'
        403:
          $ref: '#/components/responses/AccessDenied'
        404:
          $ref: '#/components/responses/NotFound'
        429:
          $ref: '#/components/responses/429'
    delete:
      x-readonly-method: false
      x-category: marketplace
      tags:
        - 'Метаданные Самовывоз'
      summary: 'Удалить метаданные сборочного задания'
      deprecated: true
      description: |
        Данный метод устарел. Он будет удалён [19 мая](https://dev.wildberries.ru/release-notes?id=474)
      parameters:
        -
          name: orderId
          in: path
          description: 'ID сборочного задания'
          required: true
          schema:
            type: integer
        -
          name: key
          in: query
          description: |
            Название метаданных для удаления (`imei`, `uin`, `gtin`, `sgtin`).
            Передается только одно значение.
          required: true
          schema:
            type: string
      responses:
        204:
          description: Удалено
        401:
          $ref: '#/components/responses/401'
        402:
          $ref: '#/components/responses/402'
        403:
          $ref: '#/components/responses/AccessDenied'
        404:
          $ref: '#/components/responses/NotFound'
        429:
          $ref: '#/components/responses/429'
  '/api/v3/click-collect/orders/{orderId}/meta/sgtin':
    put:
      x-readonly-method: false
      x-category: marketplace
      tags:
        - 'Метаданные Самовывоз'
      summary: 'Закрепить за сборочным заданием код маркировки товара'
      deprecated: true
      description: |
        Данный метод устарел. Он будет удалён [19 мая](https://dev.wildberries.ru/release-notes?id=474)
      parameters:
        -
          name: orderId
          in: path
          description: 'ID сборочного задания'
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api.SGTINsRequest'
        required: true
      responses:
        204:
          description: Обновлено
        400:
          description: 'Неправильный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                IncorrectRequestBody:
                  $ref: '#/components/examples/IncorrectRequestBody'
                IncorrectRequest:
                  $ref: '#/components/examples/IncorrectRequest'
                IncorrectParameter:
                  $ref: '#/components/examples/IncorrectParameter'
        401:
          $ref: '#/components/responses/401'
        402:
          $ref: '#/components/responses/402'
        403:
          $ref: '#/components/responses/AccessDenied'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          description: 'Ошибка добавления маркировки.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                FailedToUpdateMeta:
                  $ref: '#/components/examples/FailedToUpdateMeta'
        429:
          $ref: '#/components/responses/429'
  '/api/v3/click-collect/orders/{orderId}/meta/uin':
    put:
      x-readonly-method: false
      x-category: marketplace
      tags:
        - 'Метаданные Самовывоз'
      summary: 'Закрепить за сборочным заданием УИН (уникальный идентификационный номер)'
      deprecated: true
      description: |
        Данный метод устарел. Он будет удалён [19 мая](https://dev.wildberries.ru/release-notes?id=474)
      parameters:
        -
          name: orderId
          in: path
          description: 'ID сборочного задания'
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api.UINRequest'
        required: true
      responses:
        204:
          description: Обновлено
        400:
          description: 'Неправильный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                IncorrectRequestBody:
                  $ref: '#/components/examples/IncorrectRequestBody'
                IncorrectRequest:
                  $ref: '#/components/examples/IncorrectRequest'
                IncorrectParameter:
                  $ref: '#/components/examples/IncorrectParameter'
        401:
          $ref: '#/components/responses/401'
        402:
          $ref: '#/components/responses/402'
        403:
          $ref: '#/components/responses/AccessDenied'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          description: 'Ошибка добавления маркировки.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                FailedToUpdateMeta:
                  $ref: '#/components/examples/FailedToUpdateMeta'
        429:
          $ref: '#/components/responses/429'
  '/api/v3/click-collect/orders/{orderId}/meta/imei':
    put:
      x-readonly-method: false
      x-category: marketplace
      tags:
        - 'Метаданные Самовывоз'
      summary: 'Закрепить за сборочным заданием IMEI'
      deprecated: true
      description: |
        Данный метод устарел. Он будет удалён [19 мая](https://dev.wildberries.ru/release-notes?id=474)
      parameters:
        -
          name: orderId
          in: path
          description: 'ID сборочного задания'
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api.IMEIRequest'
        required: true
      responses:
        204:
          description: Обновлено
        400:
          description: 'Неправильный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                IncorrectRequestBody:
                  $ref: '#/components/examples/IncorrectRequestBody'
                IncorrectRequest:
                  $ref: '#/components/examples/IncorrectRequest'
                IncorrectParameter:
                  $ref: '#/components/examples/IncorrectParameter'
        401:
          $ref: '#/components/responses/401'
        402:
          $ref: '#/components/responses/402'
        403:
          $ref: '#/components/responses/AccessDenied'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          description: 'Ошибка добавления маркировки.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                FailedToUpdateMeta:
                  $ref: '#/components/examples/FailedToUpdateMeta'
        429:
          $ref: '#/components/responses/429'
  '/api/v3/click-collect/orders/{orderId}/meta/gtin':
    put:
      x-readonly-method: false
      x-category: marketplace
      tags:
        - 'Метаданные Самовывоз'
      summary: 'Закрепить за сборочным заданием GTIN'
      deprecated: true
      description: |
        Данный метод устарел. Он будет удалён [19 мая](https://dev.wildberries.ru/release-notes?id=474)
      parameters:
        -
          name: orderId
          in: path
          description: 'ID сборочного задания'
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api.GTINRequest'
        required: true
      responses:
        204:
          description: Обновлено
        400:
          description: 'Неправильный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                IncorrectRequestBody:
                  $ref: '#/components/examples/IncorrectRequestBody'
                IncorrectRequest:
                  $ref: '#/components/examples/IncorrectRequest'
                IncorrectParameter:
                  $ref: '#/components/examples/IncorrectParameter'
        401:
          $ref: '#/components/responses/401'
        402:
          $ref: '#/components/responses/402'
        403:
          $ref: '#/components/responses/AccessDenied'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          description: 'Ошибка добавления маркировки.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                FailedToUpdateMeta:
                  $ref: '#/components/examples/FailedToUpdateMeta'
        429:
          $ref: '#/components/responses/429'
components:
  schemas:
    Error:
      type: object
      nullable: false
      properties:
        code:
          type: string
          description: 'Код ошибки'
          nullable: false
        message:
          type: string
          description: 'Описание ошибки'
          nullable: false
        data:
          type: object
          description: 'Дополнительные данные, обогащающие ошибку'
          nullable: true
    api.OrdersRequest:
      type: object
      properties:
        orders:
          type: array
          description: 'Список ID сборочных заданий'
          items:
            type: integer
      example:
        orders:
          - 1234567
    api.OrderStatuses:
      type: object
      properties:
        orders:
          type: array
          description: 'Список статусов сборочных заданий'
          items:
            $ref: '#/components/schemas/api.OrderStatus'
    api.OrderStatus:
      type: object
      properties:
        id:
          type: integer
          description: 'ID сборочного задания'
        supplierStatus:
          type: string
          description: 'Статус сборочного задания, установленный продавцом'
        wbStatus:
          type: string
          description: 'Статус сборочного задания в системе WB'
      example:
        supplierStatus: confirm
        wbStatus: waiting
        id: 1234567
    api.OrdersRequestV2:
      properties:
        ordersIds:
          description: 'Список ID сборочных заданий'
          example:
            - 123456
            - 234567
          maxItems: 1000
          type: array
          items:
            type: integer
      type: object
    api.OrdersMetaResponse:
      type: object
      required:
        - meta
      properties:
        meta:
          type: array
          description: 'Метаданные сборочных заданий'
          items:
            $ref: '#/components/schemas/api.OrderMetaV2'
    api.OrderMetaV2:
      type: object
      required:
        - error
        - orderId
      properties:
        error:
          type: string
          description: |
            Сообщение об ошибке. <br>
            - `""` — нет ошибок
            - `NotFound` — сборочное задание не найдено
          example: ''
        gtin:
          type: string
          nullable: true
          description: GTIN
          example: '123456789012345'
        imei:
          type: string
          nullable: true
          description: IMEI
          example: '123456789012345'
        orderId:
          type: integer
          description: 'ID сборочного задания'
          example: 654321
        sgtin:
          type: array
          nullable: true
          description: 'Код маркировки Честного знака'
          items:
            type: string
            example: '123456789012345'
        uin:
          type: string
          nullable: true
          description: УИН
          example: '123456789012345'
    api.BatchError:
      type: object
      required:
        - origin
        - requestId
        - title
      properties:
        detail:
          type: object
          nullable: true
          description: 'Детали ошибки'
          example: {  }
        origin:
          type: string
          description: 'ID внутреннего сервиса WB'
          example: market-public-api
        requestId:
          type: string
          description: 'Уникальный ID запроса'
          example: f1787bd2d1fdс35d6f537316514у4a05
        title:
          type: string
          description: 'Заголовок ошибки'
          example: IncorrectRequest
    api.OrdersMeta:
      type: object
      properties:
        meta:
          type: object
          description: 'Метаданные сборочного задания'
          allOf:
            -
              $ref: '#/components/schemas/api.baseMeta'
    api.baseMeta:
      type: object
      properties:
        gtin:
          type: object
          properties:
            value:
              nullable: true
              type: string
              example: '123456789012345'
          description: GTIN
        imei:
          type: object
          properties:
            value:
              nullable: true
              type: string
              example: '123456789012345'
          description: IMEI
        sgtin:
          type: object
          properties:
            value:
              type: array
              items:
                type: string
              example:
                - '123456789012345'
              nullable: true
          description: 'Код маркировки Честного знака'
        uin:
          type: object
          properties:
            value:
              nullable: true
              type: string
              example: '123456789012345'
          description: УИН
    api.SGTINsRequest:
      type: object
      properties:
        sgtins:
          type: array
          description: 'Массив кодов маркировки. Допускается от 16 до 135 символов для кода одной маркировки'
          items:
            type: string
      example:
        sgtins:
          - '1234567890123456'
    api.UINRequest:
      type: object
      properties:
        uin:
          type: string
          description: УИН
      example:
        uin: '1234567890123456'
    api.IMEIRequest:
      type: object
      properties:
        imei:
          type: string
          description: IMEI
      example:
        imei: '123456789012345'
    api.GTINRequest:
      type: object
      properties:
        gtin:
          type: string
          description: GTIN
      example:
        gtin: '1234567890123456'
  examples:
    IncorrectParameter:
      value:
        code: IncorrectParameter
        message: 'Передан некорректный параметр'
    StatusMismatch:
      value:
        code: StatusMismatch
        message: 'Несоответствие статусов, проверьте их правильность'
    IncorrectRequestBody:
      value:
        code: IncorrectRequestBody
        message: 'Некорректное тело запроса'
    IncorrectRequest:
      value:
        code: IncorrectRequest
        message: 'Переданы некорректные данные'
    FailedToUpdateMeta:
      value:
        code: FailedToUpdateMeta
        message: 'Не удалось обновить метаданные сборочного задания. Убедитесь, что сборочное задание удовлетворяет всем необходимым требованиям (сборочное задание существует, находится в статусе "На сборке", сборочному заданию доступны метаданные см. описание метода **Получить метаданные сборочного задания**)'
  responses:
    401:
      description: 'Не авторизован'
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              title:
                type: string
                description: 'Заголовок ошибки'
              detail:
                type: string
                description: 'Детали ошибки'
              code:
                type: string
                description: 'Внутренний код ошибки'
              requestId:
                type: string
                description: 'Уникальный ID запроса'
              origin:
                type: string
                description: 'ID внутреннего сервиса WB'
              status:
                type: number
                description: 'HTTP статус-код'
              statusText:
                type: string
                description: 'Расшифровка HTTP статус-кода'
              timestamp:
                type: string
                format: date-time
                description: 'Дата и время запроса'
          example:
            title: unauthorized
            detail: 'token problem; token is malformed: could not base64 decode signature: illegal base64 data at input byte 84'
            code: '07e4668e--a53a3d31f8b0-[UK-oWaVDUqNrKG]; 03bce=277; 84bd353bf-75'
            requestId: 7b80742415072fe8b6b7f7761f1d1211
            origin: s2s-api-auth-catalog
            status: 401
            statusText: Unauthorized
            timestamp: '2024-09-30T06:52:38Z'
    402:
      description: 'Требуется платёж'
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              title:
                type: string
                description: 'Заголовок ошибки'
              detail:
                type: string
                description: 'Детали ошибки. Ошибка означает, что на балансе сервиса из [Каталога](https://dev.wildberries.ru/business-solutions) недостаточно средств'
          example:
            title: 'payment required'
            detail: 'please top up your balance in your company personal account https://dev.{{ .baseDomain }}/company'
    AccessDenied:
      description: 'Доступ запрещён'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: AccessDenied
            message: 'Доступ запрещён'
    NotFound:
      description: 'Не найдено'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: NotFound
            message: 'Not Found'
    429:
      description: 'Слишком много запросов'
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              title:
                type: string
                description: 'Заголовок ошибки'
              detail:
                type: string
                description: 'Детали ошибки'
              code:
                type: string
                description: 'Внутренний код ошибки'
              requestId:
                type: string
                description: 'Уникальный ID запроса'
              origin:
                type: string
                description: 'ID внутреннего сервиса WB'
              status:
                type: number
                description: 'HTTP статус-код'
              statusText:
                type: string
                description: 'Расшифровка HTTP статус-кода'
              timestamp:
                type: string
                format: date-time
                description: 'Дата и время запроса'
          example:
            title: 'too many requests'
            detail: 'limited by c122a060-a7fb-4bb4-abb0-32fd4e18d489'
            code: '07e4668e-ac2242c5c8c5-[UK-4dx7JUdskGZ]'
            requestId: 9d3c02cc698f8b041c661a7c28bed293
            origin: s2s-api-auth-catalog
            status: 429
            statusText: 'Too Many Requests'
            timestamp: '2024-09-30T06:52:38Z'
    IncorrectRequest:
      description: 'Неправильный запрос'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.BatchError'
          example:
            detail: {  }
            origin: market-public-api
            requestId: f1787bd2d1fdс35d6f537316514у4a05
            title: IncorrectRequest
    AccessDeniedBatch:
      description: 'Доступ запрещён'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.BatchError'
          example:
            detail: {  }
            origin: market-public-api
            requestId: f1787bd2d1fdс35d6f537316514у4a05
            title: AccessDenied
